---
title: "Applied Data Analysis"
subtitle: "Text mining with R!"
author: "Tomáš Oleš"
institute: "Department of Economic Policy"
date: "2025"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: atom-one-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
#See slide on xaringanthemer
library(xaringanthemer)
# style_duo_accent(
# primary_color = "#d19f2a",     # KHP color
# secondary_color = "#e2c47c",   # KHP light
style_mono_accent(
base_color = "#002147",
header_font_google = google_font("Josefin Sans"),
text_font_google = google_font("Montserrat", "300", "300i"),
code_font_google = google_font("Fira Mono")
)

```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
# Remember to compile
#xaringan::inf_mr(cast_from = "..")
#       slideNumberFormat: ""  
library(tidyverse)
if (!require("emo")) devtools::install_github("")
library(emo)
library(DiagrammeR)
library(Tmisc)
library(ggplot2)
library(gridExtra)
if (!require("dsbox")) devtools::install_github("rstudio-education/dsbox")
library(dsbox)
library(palmerpenguins)
```

```{r  echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(fig.retina = 5)
```


# `r emo::ji('construction')` `r emo::ji('clapper')` `r emo::ji('construction')` `r emo::ji('smile')`

---
# Sources
- [Silge, J., Robinson D. (2025). Text Mining with R!. O'Reilly](https://www.tidytextmining.com/)

---