---
title: "Joining, tidying"
author: "Tomas Oles"
date: "2025-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
starwars

starwars %>%
  select(sex, name, mass)


starwars %>%
  select(sex, height) %>%
  group_by(sex) %>%
  summarise(avg_height = mean(height, na.rm = T))

df = data.frame("a" = 1:5, "b 2" = 5:1)
#View(df)
class(df)

ti = tibble("a" = 1:5, "b 2" = 5:1)
#View(ti)
class(ti)

df$c 
ti$c

df[,1]
ti[,1]

df$b 
ti$b

df = data.frame(l1=letters[1:5])
class(df$l1)



```

# Data wrangling 

```{r}
library(dplyr)
library(tidyverse)

hotels <- read_csv("data/hotels.csv")
class(hotels)

hotels <- read.csv("data/hotels.csv")
class(hotels)

hotels <- tibble(hotels)
class(hotels)

hotels
glimpse(hotels)

  
unique(hotels$hotel)

hotels %>%
  filter(hotel == "Resort Hotel") %>%
  lm(adr ~ lead_time, data = .)

hotel_subset <- hotels %>% 
  select(hotel, lead_time, adr)


hotels %>%
  select(adults, children, babies, lead_time) %>%
  arrange(desc(babies))

hotels %>%
  group_by(babies) %>%
  summarise(avg_lead_time = mean(lead_time, na.rm=T))


hotels %>%
  select(adults, children, babies, lead_time) %>%
  arrange(desc(babies)) %>%
  slice(1:5)


nrow <- nrow(hotels)
hotels %>%
  slice((nrow-1):nrow)

hotels %>%
  select(adults, children, babies) %>%
  filter(adults == 0, babies >= 1 | children >= 1)

hotels %>% 
  distinct(hotel, market_segment) %>%
  arrange(market_segment)

hotels %>%
  count(hotel, market_segment)

hotels %>%
  mutate(little_ones = log(children + babies)) %>%
  arrange(desc(little_ones)) 


names(hotels)

hotels %>%
  group_by(arrival_date_year) %>%
  summarise(m_adr = mean(adr)) %>%
  mutate(m_adj_adj = m_adr/102)




```
# Joining 
```{r}

```


```{r}

```


```{r}

```


```{r}

```



