---
title: "Seminar 2 - Tomas"
author: "Tomas Oles"
date: "2024-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(palmerpenguins)
library(tidyverse)
library(dplyr)
```

## Moj prvy R markdown

Tu si budem napriklad pisat poznamky 

```{r}
options(tibble.print_min = 10)
heights = read_csv("data/highest-points-by-state.csv")
heights$elevation = heights$elevation * .3048
heights

arrange(heights, elevation)
arrange(heights, desc(elevation))



ggplot(heights,  aes(x = elevation)) +
    geom_density() +
    geom_rug()
```
```{r}
starwars <- starwars 
starwars 
glimpse(starwars)

```



```{r}
ggplot(starwars, mapping = aes(x=height, y = mass))+
  geom_point()
```
```{r}
penguins <- penguins
glimpse(penguins)

ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, y = bill_length_mm,
                     color = species, shape = island, size = body_mass_g, alpha = flipper_length_mm)) +
  geom_point() +
  labs(title="Vztah medzi vyskou a sirkou zobacika") +
  scale_color_viridis_d()



ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, y = bill_length_mm)) +
  geom_point(size= 2, alpha = 0.5) +
  labs(title="Vztah medzi vyskou a sirkou zobacika") +
  scale_color_viridis_d()


ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, y = bill_length_mm)) +
  geom_point(size= 2, alpha = 0.5) +
  labs(title="Vztah medzi vyskou a sirkou zobacika") +
  scale_color_viridis_d() +
  facet_grid(species ~ island)
```




```{r}

loans_full_schema <- read.csv(file = "data/loans_data.csv")

loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, 
         state, annual_income, homeownership, debt_to_income)


ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 5000, alpha = 0.5)


ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
  geom_histogram(binwidth = 5000, alpha = 0.5)


ggplot(loans, aes(x = loan_amount, fill = homeownership,)) +
  geom_histogram(binwidth = 5000, alpha = 0.7)+
facet_wrap(~ homeownership, nrow = 3)

summary(loans$loan_amount)


ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 2)

ggplot(loans, aes(x = loan_amount, 
                  fill = homeownership)) +
  geom_density(adjust = 2, 
               alpha = 0.5) 
```




# Vizualizacia Palmer Pinguins

Ciel je pochopit gramatiku grafiky (ggplop)


```{r}
library(tidyverse)
library(dplyr)
library(palmerpenguins)

ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
  geom_point() 



ggplot(mapping = aes(x = bill_depth_mm, y = bill_length_mm, color = species, shape = island,  size = body_mass_g, alpha = flipper_length_mm), data = penguins) +
  geom_point(alpha = 0.5) +
    scale_color_viridis_d()



ggplot(mapping = aes(x = bill_depth_mm, y = bill_length_mm), data = penguins) +
  geom_point(size = 1, alpha = 0.5) +
  facet_grid(sex ~ species)



```

## Loans data 

```{r message=TRUE, warning=FALSE}
loans_full_schema <- read.csv(file = "data/loans_data.csv")


ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 5000)

ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 2)

```
